on:
  push:
    tags:
      - '*-*-*'

name: Create release draft

env:
  NODE_VERSION: 24

jobs:
  build:
    name: Create release from tag
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v7

      - name: use node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Ensure our node version matches the main repo's version
        run: |
          curl -s https://raw.githubusercontent.com/opencast/opencast/refs/heads/${{ github.ref_name }}/pom.xml -o pom.xml
          export FOUND_VERSION="$(grep node.version pom.xml | grep -Eo 'v[0-9.]+' | cut -f 1 -d '.' | cut -c 2-)"
          [[ "$FOUND_VERSION" == "$NODE_VERSION" ]] \
          && exit 0 \
          || (echo "Node version does not match.  Expected $NODE_VERSION, found $FOUND_VERSION"; exit 1)

      - name: create release tarball
        run: echo 'y' | ./.github/create-release.sh

      - name: create new release
        uses: softprops/action-gh-release@v3
        with:
          files: oc-studio-*.tar.gz
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: true
